FROM j-ubuntu20.04-python3

MAINTAINER JackonYang <i@jackon.me>

RUN pip install \
    ipython \
    jupyter \
    numpy \
    pandas \
    scipy \
    scikit-learn \
    matplotlib \
    Pillow \
    seaborn
