PY?=python3

docker-build:
	bash scripts/docker-build.sh

docker-run:
	bash scripts/docker-run.sh

docker-cuda-run:
	bash scripts/docker-cuda-run.sh

docker-push:
	bash scripts/docker-push.sh


.PHONY: docker-build docker-run docker-push
