name: Docker Image CI

on:
  push:
    branches:
        - project/**
  pull_request:
    branches:
        - project/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: bash publish_branch_image.sh
      env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
